from .config import *

_ASSET_ROLES = ("character", "background", "item")


class _CodexImagePacer:
    """Waits CODEX_IMAGE_DELAY seconds between successive Codex image calls
    (references + scenes, across one seed) to stay under its usage limit.
    The first call in a run never waits. Logs clearly around each pause so
    it reads as an intentional, expected wait — not the process being stuck."""

    def __init__(self):
        self._first = True

    def wait(self):
        if self._first:
            self._first = False
            return
        minutes = CODEX_IMAGE_DELAY / 60
        log.info(
            f"[image] Pausing {minutes:.0f} minute(s) before the next image — "
            f"this is intentional, to stay under Codex's usage limit. Not stuck, "
            f"just waiting."
        )
        time.sleep(CODEX_IMAGE_DELAY)
        log.info("[image] Resuming image generation now.")


def _derive_asset_refs(seed_id: int, cursor) -> SceneAssetRefs:
    """Ask the LLM to distill one consistent character/background/item
    description from a seed's already-generated scene image prompts, so
    every scene can be composed from the same set instead of each looking
    different (see _ensure_asset_refs)."""
    cursor.execute(
        "SELECT sceneNumber, sceneImage FROM scene WHERE seedId=? ORDER BY sceneNumber",
        (seed_id,),
    )
    scenes_block = "\n".join(f"Scene {n}: {desc}" for n, desc in cursor.fetchall())
    prompt = f"""Here are the image descriptions for every scene of one YouTube video:
{scenes_block}

Extract ONE consistent set of visual references reusable across every scene above, for visual continuity in generated images:
1. character: a single detailed description of the main character/subject that recurs or best fits across these scenes (species/type, appearance, clothing, colors, distinguishing features).
2. background: a single detailed description of the recurring setting/environment/atmosphere shared across the scenes.
3. item: a single detailed description of the most important recurring object or prop in the story.
"""
    raw = llm_chat(prompt, schema=SceneAssetRefs.model_json_schema())
    return SceneAssetRefs.model_validate_json(raw)


def _ensure_asset_refs(seed_id: int, cursor, pacer: "_CodexImagePacer") -> dict:
    """Generate (once per seed) and return {role: path} reference images —
    character, background, item — reused across every scene in the project
    for visual consistency. Skipped if already generated by a prior run."""
    ref_dir = f"{BASE_DIR}/temp/image/refs/{seed_id}"
    os.makedirs(ref_dir, exist_ok=True)
    paths = {role: os.path.join(ref_dir, f"{role}.png") for role in _ASSET_ROLES}
    if all(os.path.exists(p) for p in paths.values()):
        return paths

    from .codex_provider import codex_generate_image
    refs = _derive_asset_refs(seed_id, cursor)
    descriptions = {"character": refs.character, "background": refs.background, "item": refs.item}
    for role, path in paths.items():
        if os.path.exists(path):
            continue
        pacer.wait()
        log.info(f"[image] Generating {role} reference for seed {seed_id}")
        codex_generate_image(descriptions[role], path, require_portrait=False)
    return paths


def image_generate_for_seed(seed_id: int):
    """Generate one PNG per scene that hasn't been imaged yet.

    Uses Flux (local, diffusers), the OpenAI Images API, or Codex's built-in
    image_gen tool, per IMAGE_PROVIDER.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT taskId, sceneNumber FROM task "
        "WHERE sceneImageDate='0000-00-00 00:00:00' AND seedId=?",
        (seed_id,),
    )
    tasks = cursor.fetchall()

    if not tasks:
        conn.close()
        return

    pipe = get_flux_pipe() if IMAGE_PROVIDER == "flux" else None
    pacer = _CodexImagePacer() if IMAGE_PROVIDER == "codex" else None
    asset_refs = _ensure_asset_refs(seed_id, cursor, pacer) if IMAGE_PROVIDER == "codex" else None

    for task_id, scene_number in tasks:
        cursor.execute(
            "SELECT sceneId, sceneImage FROM scene WHERE seedId=? AND sceneNumber=?",
            (seed_id, scene_number),
        )
        row = cursor.fetchone()
        if not row:
            continue
        scene_id, scene_image_prompt = row

        out_dir = f"{BASE_DIR}/temp/image/{scene_id}"
        os.makedirs(out_dir, exist_ok=True)
        image_path = os.path.join(out_dir, "image.png")

        if os.path.exists(image_path):
            # A prior run's generation can land on disk after we'd already
            # given up on it (e.g. a Codex call that finished right as its
            # timeout fired) — pick that up instead of paying for a
            # redundant regeneration.
            log.info(f"[image] Scene {scene_number} (task {task_id}) already has an image on disk, marking done")
            cursor.execute(
                "UPDATE task SET sceneImageDate=datetime('now','localtime') WHERE taskId=?",
                (task_id,),
            )
            conn.commit()
            continue

        full_prompt = scene_image_prompt
        # Append negative guidance as a separate "negative" token block if supported;
        # Flux is a guidance-distilled model – negative prompt has no official channel,
        # so we append style cues to the positive prompt instead.
        full_prompt += f", high quality, sharp, professional photography, cinematic"

        log.info(f"[image] Generating scene {scene_number} (task {task_id}): {scene_image_prompt[:80]}…")
        try:
            if IMAGE_PROVIDER == "openai":
                from .openai_image import openai_generate_image
                openai_generate_image(full_prompt, image_path)
            elif IMAGE_PROVIDER == "codex":
                from .codex_provider import codex_generate_image
                pacer.wait()
                references = [(role, asset_refs[role]) for role in _ASSET_ROLES]
                codex_generate_image(full_prompt, image_path, references=references)
            else:
                import torch
                result = pipe(
                    prompt=full_prompt,
                    height=FLUX_HEIGHT,
                    width=FLUX_WIDTH,
                    num_inference_steps=FLUX_STEPS,
                    guidance_scale=FLUX_GUIDANCE,
                    generator=torch.Generator().manual_seed(random.randint(0, 2**32 - 1)),
                )
                image = result.images[0]
                image.save(image_path)
            log.info(f"[image] Saved: {image_path}")

            cursor.execute(
                "UPDATE task SET sceneImageDate=datetime('now','localtime') WHERE taskId=?",
                (task_id,),
            )
            conn.commit()
        except Exception as e:
            log.error(f"[image] Generation failed for taskId {task_id}: {e}")
            # Every other module (voice/clip/subtitle/...) calls this on
            # failure so the seed surfaces as "needs attention" instead of
            # sitting in "in progress" forever with nothing to explain why —
            # this loop was the one place that only logged and moved on.
            mark_seed_error(seed_id, "image", f"Scene {scene_number} (task {task_id}): {e}")

    conn.close()


def run_image():
    """Run the Image module for all pending seeds."""
    log.info("═══ MODULE: IMAGE ═══")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        """SELECT DISTINCT seedId FROM task
           WHERE sceneImageDate='0000-00-00 00:00:00'
           AND sceneAudioDate='0000-00-00 00:00:00'
           AND sceneClipDate='0000-00-00 00:00:00'
           AND sceneSubtitleDate='0000-00-00 00:00:00'"""
    )
    seeds = cursor.fetchall()
    conn.close()
    log.info(f"[image] {len(seeds)} pending seeds")
    for (seed_id,) in seeds:
        try:
            image_generate_for_seed(seed_id)
        except Exception as e:
            log.error(f"[image] Seed {seed_id} failed: {e}")
            mark_seed_error(seed_id, "image", str(e))
